[package]
name = "rust-kernel"
version = "0.1.0"
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
vga = "0.2.6"
ryu = "1.0"

[lib]
crate-type = ["staticlib"]
path = "main.rs"
